CREATE TABLE employees (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    commision_num INTEGER NOT NULL,
    work_email TEXT NOT NULL,
    password TEXT NOT NULL
);